class SiteCollection:
    jsonWebSite = """{"project_list":[
                                      {  "projectname"  : "Dade Tamin",
                                         "projecturl"   : "http://www.datatamin.ir" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com",
                                         "CellPhones"   : "09143011491",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "EkramOnline",
                                         "projecturl"   : "https://ekram.emdad.ir" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,v_nasiry@yahoo.com,s.jabbari77@gmail.com",
                                         "CellPhones"   : "09143011491,09144023083,09014635773",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "EkramBank",
                                         "projecturl"   : "http://91.224.111.79/api/values" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,v_nasiry@yahoo.com,s.jabbari77@gmail.com",
                                         "CellPhones"   : "09143011491,09144023083,09014635773",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "nikookari",
                                         "projecturl"   : "http://nikookari.ikrf.ir/nikookari" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,v_nasiry@yahoo.com,s.jabbari77@gmail.com",
                                         "CellPhones"   : "09143011491,09144023083,09014635773",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "nikookari_firewall",
                                         "projecturl"   : "http://91.224.110.203" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,v_nasiry@yahoo.com,s.jabbari77@gmail.com",
                                         "CellPhones"   : "09143011491,09144023083,09014635773",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
				                      {  "projectname"  : "Tamin",
                                         "projecturl"   : "http://law.tamin.ir/ho" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,hekmatyy@gmail.com,s.jabbari77@gmail.com",
                                         "CellPhones"   : "09143011491,09149028858",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },

                                      {  "projectname"  : "Sajma",
                                         "projecturl"   : "https://sajma.abfaazarbaijan.ir/sys/fa/rmax/login/login" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,hekmatyy@gmail.com",
                                         "CellPhones"   : "09143011491,09149028858",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "Kish Legal",
                                         "projecturl"   : "http://109.230.79.70:3227/syskishlaw/fa/rmax/login/login" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,hekmatyy@gmail.com,me.hosseinzadeh@yahoo.com",
                                         "CellPhones"   : "09143011491,09149028858,09147852001",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      },
                                      {  "projectname"  : "Abfa Pmis",
                                         "projecturl"   : "https://sajma.abfaazarbaijan.ir/syspmis/fa/rmax/login/login" ,
                                         "Receivers"    : "a.gharakhanlou@gmail.com,hekmatyy@gmail.com,me.hosseinzadeh@yahoo.com",
                                         "CellPhones"   : "09143011491,09149028858,09147852001",
                                         "errmsg"       : "",
                                         "statuscode"   : "0",
                                         "cpu"          : "0",
                                         "hdd"          : "0",
                                         "mem"          : "0",
                                         "dbcon"        : "0",
                                         "lstbackup"    : "0",
                                         "serial1"      : "",
                                         "serial2"      : ""
                                      }
                                      
                                      
                                  ]
                }"""
